version: '3'

services:
  frontend:
    image: rumeebs23/frontend:latest
    container_name: frontend_container
    ports:
      - "3000:3000"
    networks:
      frontend-backend:
        ipv4_address: 172.50.0.2

  backend:
    image: rumeebs23/backend:latest
    container_name: backend_container
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=todo
      - POSTGRES_USER=todo
      - POSTGRES_PASSWORD=todo
    networks:
      frontend-backend:
        ipv4_address: 172.50.0.3
    depends_on:
      - db

  db:
    image: postgres
    container_name: database
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      frontend-backend:
        ipv4_address: 172.50.0.4

networks:
  frontend-backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.50.0.0/16

volumes:
  postgres_data:
