name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build_and_push_images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend Docker Image
        run: |
          # Build the backend Docker image
          docker build -t rumeebs23/backend:latest -f ./backend/djangoproject/Dockerfile ./backend/djangoproject
          # Push the backend Docker image to Docker Hub
          docker push rumeebs23/backend:latest
  

      - name: Build Frontend Docker Image
        run: |
          # Build the frontend Docker image
          docker build -t rumeebs23/frontend:latest -f ./frontend/todo/Dockerfile ./frontend/todo
          # Push the frontend Docker image to Docker Hub
          docker push rumeebs23/frontend:latest
